title: Default Page

tabs:
    content:
        label: Content
        icon: text
        columns:
          - width: 2/3
            sections:
                content:
                    type: fields
                    fields:
                        text:
                            extends: fields/fulleditor
                        gallery:
                            extends: fields/gallery
                subpages:
                    headline: Subpages
                    type: pages
                    status: all
                    templates: default

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
