title: Site

tabs:
    content:
        label: Content
        icon: text
        columns:
          - width: 2/3
            sections:
                homepage:
                    headline: Home
                    type: pages
                    status: all
                    templates: home
                    max: 1
                allpages:
                    headline: Pages
                    type: pages
                    status: all
                    templates: default
                itemsections:
                    headline: Sections
                    type: pages
                    status: all
                    templates: itemsection
                blog:
                    headline: Articles
                    type: pages
                    status: all
                    templates: article
                    parent: site.find("news")
                studentworks:
                    headline: Student Works
                    type: pages
                    status: all
                    template: students
                    parent: site.find('seminars')
                    max: 1
                contact:
                    headline: Contact
                    type: pages
                    status: all
                    templates: contact
                    max: 1
          - width: 1/3
            sections:
                menu:
                    headline: Menu
                    type: pages
                    status: all
                    templates:
                      - default
                      - itemsection
                      - blog
                      - contact
                pagefiles:
                    extends: sections/pagefiles
    seo:
        label: SEO
        icon: search
        columns:
          - width: 2/3
            sections:
                siteseo:
                    type: fields
                    fields:
                        sitetwitter:
                            type: text
                            label: Site Twitter Username
                        facebook:
                            type: url
                            label: Facebook Page
                        twitter:
                            type: url
                            label: Site Twitter Page
                        instagram:
                            type: url
                            label: Instagram Page
                        pinterest:
                            type: url
                            label: Pinterest Page
                        linkedin:
                            type: url
                            label: LinkedIn Page
